services:
  db:
    image: mariadb:latest
    container_name: dwese-gymsolucar-webapp-db-1
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    name: dwese-gymsolucar-webapp_default